# Generated by Django 2.1.7 on 2019-03-16 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LikedRecepy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('cuisines', models.CharField(max_length=500)),
                ('vegan', models.BooleanField()),
                ('image', models.CharField(max_length=200)),
                ('vegetarian', models.BooleanField()),
                ('ingredients', models.CharField(max_length=1000)),
                ('glutenFree', models.BooleanField()),
                ('calories', models.PositiveIntegerField()),
                ('fat', models.PositiveIntegerField()),
                ('carb', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StepCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepCount', models.PositiveIntegerField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmigoal', models.FloatField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('cuisine', models.CharField(max_length=2000)),
                ('targetWeight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('timestamp', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User')),
            ],
        ),
        migrations.AddField(
            model_name='stepcount',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User'),
        ),
        migrations.AddField(
            model_name='locations',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User'),
        ),
        migrations.AddField(
            model_name='likedrecepy',
            name='recipeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Recipe'),
        ),
        migrations.AddField(
            model_name='likedrecepy',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User'),
        ),
    ]
