# Generated by Django 2.1.7 on 2019-03-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StepCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepCount', models.PositiveIntegerField()),
                ('timestamp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='stepcount',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User'),
        ),
        migrations.AddField(
            model_name='locations',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User'),
        ),
    ]
